// web/src/Home.jsx
import {React} from 'reactrx';
import s from 'css/home';
import {logout, verifySession} from 'client';

const Home = ({setRoute, Link}) => {
  verifySession().catch(ex => setRoute("/login"));
  const logout2 = () => logout().then(() => setRoute("/"));
  return (
    <div class={s.home}>
      <Link href="/task" class={s.button}>Task</Link>
      <button onclick={logout2} class={s.button}>Logout</button>
    </div>
  );
};

export default Home;

// web/src/views/Home.vue
<template>
<div class="home flex-column border">
  <router-link class="row button" :to="{name: 'task'}">Tasks</router-link>
  <router-link class="row button" :to="{name: 'list-article'}">Articles</router-link>
  <button class="row button" v-on:click="logout">Logout</button>
</div>
</template>

<script lang="ts">
import {Component, Vue} from 'vue-property-decorator';
import {verifySession, clearSession} from '@/client.ts';

@Component
export default class Login extends Vue {
  private mounted() {
    verifySession()
        .catch(() => {
          this.$router.push({name: 'login'});
        });
  }

  private logout() {
    clearSession()
        .then(() => {
          this.$router.push({name: 'start'});
        });
  }
}
</script>

<style scoped>
.home {
  width: 20em;
  margin: 50px auto;
  padding: 0 10px;
  background-color: aliceblue;
}

.row {
  margin: 30px 0;
  width: 10em;
}
</style>
